### ISSUE TITLE
No longer working with anki v2.1.35

### ISSUE THREAD

**Issue by skywalkercode** [yukach/anki21-addon-customize-sidebar#12]
Randomly stopped working today and many others commenting the same on the ankiweb page https://ankiweb.net/shared/info/1988760596

Updating to 2.1.39 fixed like the add-on page wanted, but updating breaks other add-ons I have currently. Any way to enable this for 2.1.35 again since it was working just fine?

**Comment by cereska** [comment]
Up. I'd really love it working again on 2.1.35 too, I can't upgrade due to other add-ons either :( 
Can you perhaps add a tag to the previous release (v.1.2.0), so that others in the same situation can download it easily? Many thanks in advance!

**Comment by yukach** [comment]
ok, I will prepare release for v.2.1.35

**Comment by yukach** [comment]
Damn, the addon is not broken. Just I set wrong minimal ver in the addon description, fixed. please check.

**Comment by cereska** [comment]
Deleted and redownloaded the addon - can confirm that it works again on 2.1.35. Thank you so much for looking into it!

**Comment by yukach** [comment]
close, it was inccorrect addon descrption
