### ISSUE TITLE
Port to 2.1.17

### ISSUE THREAD

**Issue by starwarsstan** [yukach/anki21-addon-customize-sidebar#5]
This is currently not supported in 2.1.17

Any chance that will happen soon?

**Comment by AnKingMed** [comment]
I would also like to know your estimated timing on this if at all possible

**Comment by yukach** [comment]
Hi. The fix is in progress. I need couple days.

**Comment by AnKingMed** [comment]
Sounds great.  Thank you @yukach!

**Comment by yukach** [comment]
Ported. Please update the addon and test. If you find any error let me know.

**Comment by starwarsstan** [comment]
Thank you!
