### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by cjdduarte** [yukach/anki21-addon-customize-sidebar#6]
You could also group the tags.

![image](https://user-images.githubusercontent.com/42243532/72516536-99e92300-3830-11ea-9278-c062ff2b69ff.png)

**Comment by yukach** [comment]
Why don't you install https://ankiweb.net/shared/info/594329229. and use some common prefix for your tag like my::

**Comment by yukach** [comment]
I would like to know, did 'Hierarchical Tags' addon help you?

**Comment by cjdduarte** [comment]
I already used this addon.
See that structure by hierarchy, but missing a parent structure. Just as you implemented a parent structure called "decks" and "note type", you could have an equivalent called a "tag".

![image](https://user-images.githubusercontent.com/42243532/72619667-8dda8f80-391c-11ea-9de7-a3c6216f2d8a.png)

**Comment by cjdduarte** [comment]
It is no longer accurate. The other addon just implemented this. Thanks.

**Comment by yukach** [comment]
What is the name of that addon? I will look at it.
