### ISSUE TITLE
"Marked" does not work properly

### ISSUE THREAD

**Issue by ghost** [yukach/anki21-addon-customize-sidebar#8]
In German version, "Marked" does not find marked notes. Problem with capital letters?

**Comment by yukach** [comment]
Hm, I don't know. It needs to investigate. Thanks. I will take a look. What anki version do you use?

**Comment by yukach** [comment]
I tested on anki version 2.1.29 (bbff62bf) with the German locale (run as **anki -l de** in the terminal). 'Marked' works properly. Cannot reproduce.

**Comment by ghost** [comment]
There is no item "marked" (or German equivalent) in the left bar of browser to show the group. I have reinstalled Anki inclusive new Anki directory. I am using Windows 10.The vocabularies were marked (old style, not the new color marked) in Ankidroid in Smartphone Android 8.0. The synchronising works since I can find the cards in ankibrowser by alphabet. They are correctly marked, but they are not found in Anki-browser in PC since there is no keyword "marked" in the download menue neither in A-M nor in M-Z.Best regardsHolgerGib jedem Tag die Chance der schönste deines Lebens zu werden.Mark Twain Am 05.08.20, 17:21 schrieb Yury Kazakevich <notifications@github.com>:

   
  I tested on anki version 2.1.29 (bbff62bf) with the German locale (run as anki -l de in the terminal). 'Marked' works properly. Cannot reproduce.

**Comment by yukach** [comment]
Hmm, can you check the plugin's config and make sure that "show_item_marked" is true.

**Comment by yukach** [comment]
unable to reproduce
